---
- hosts: 172.31.44.7
  become: yes
  tasks:
    - include_tasks: mytestfile.yml

    - name: create a folder
      file:
        path: /home/ubuntu/myfolder
        state: directory

    - name: I want to copy files
      copy:
        src: mytestfile
        dest: /home/ubuntu/mystaticfile.txt 