---
- hosts: 172.31.44.7
  become: yes
  tasks:
    - include_tasks: mytestfile.yml

    - name: create a folder
      file:
        path: /home/ubuntu/myfolder
        state: directory

    - name: I want to copy files
      copy:
        src: mytestfile
        dest: /home/ubuntu/mystaticfile.txt 

    - name: install apache2
      apt:
        name: apache2
        state: present

    - name: copy dynamic file
      template:
        src: myindex.j2
        dest: /var/www/html/index.html

    - name: download internet files
      get_url:
        url: https://get.jenkins.io/war-stable/2.361.1/jenkins.war
        dest: /home/ubuntu
        force_basic_auth: yes
